### ISSUE TITLE
Feat:Add Missing Meta Tags, robots.txt, sitemaps for SEO Enhancement

### ISSUE THREAD

**Issue by myselfshivams** [RamakrushnaBiswal/PlayCafe#449]
### Describe the feature

The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines

we need to add the following missing meta tags:

Title tags
Description tags
Keywords tags
Open Graph tags for social media sharing
Robots meta tag

and have to add sitemap.xml and robots file for search engine to crawl our site.

### Add ScreenShots

we need to add the following missing meta tags:

Title tags
Description tags
Keywords tags
Open Graph tags for social media sharing
Robots meta tag

and have to add sitemap.xml and robots file for search engine to crawl our site.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
Go for it @myselfshivams
